[versions]
agp = "8.9.0"
kotlin = "2.0.21"


[libraries]


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

